edu:
  birzeit:
    marketplace:
        userPoolId: "us-east-1_rT2RHbx6Y"
        region: "us-east-1"
        pjwkUrl: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_rT2RHbx6Y/.well-known/jwks.json"